apiVersion: apps/v1
kind: Deployment
metadata:
  name: josh-deployment  
  namespace: homework  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: leumi
        ports:
        - containerPort: 443
